name: Nutcrackerz
favicon: null
layout_spectrum: 0.75947
typography_spectrum: 0.50671
title: 'Official Site of the Janet M. Schmidt Illinois Club, OES'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c00000'
    - '#e27e0e'
    - '#00af50'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
